---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-inspector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspector
  template:
    metadata:
      labels:
        app: inspector
    spec:
      containers:
        - name: app
          image: fastapi-inspector
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: APP_ENV
              value: "kind"

            - name: SERVICE_NAME
              value: "fastapi-inspector"

            - name: READY_AFTER
              value: "5"

            # Downward API
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          livenessProbe:
            httpGet:
              path: /live
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-inspector
spec:
  type: NodePort
  selector:
    app: inspector
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
