---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-inspector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspector
  template:
    metadata:
      labels:
        app: inspector
    spec:
      containers:
        - name: app
          image: fastapi-inspector
          imagePullPolicy: Never

          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

          # Resource limits for better cluster management
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          env:
            - name: APP_ENV
              value: "kind"

            - name: SERVICE_NAME
              value: "fastapi-inspector"

            - name: READY_AFTER
              value: "5"

            # Downward API - inject pod metadata
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          # Liveness probe - restart if unhealthy
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          # Readiness probe - control traffic routing
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          # Security context for non-root user
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-inspector
spec:
  type: NodePort
  selector:
    app: inspector
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
